name: elephantbook
channels:
  - defaults
dependencies:
  - pip=21.2.4
  - python==3.9.7
  - pip:
    - celery==5.2.0
    - django==3.2.9
    - "--editable=git+https://github.com/mavericm1/django-auditlog.git@7034ed511b25709aa68d7b1dde1cdcc4b9e4bfaf#egg=django-auditlog"
    - django-celery-results==2.2.0
    - django-extensions==3.1.5
    - django-multiselectfield==0.1.12
    - django-polymorphic==3.0.0
    - django-sslserver==0.22
    - django-storages==1.12.3
    - djangorestframework==3.12.4
    - numpy==1.21.4
    - pandas==1.3.4
    - pillow==8.2.0
    - requests==2.26.0
    - torch==1.10.0
    - torchvision==0.11.1
    - tqdm==4.62.3
